import { PublicLayout } from "@/components/layout";
import { useLogin } from "@workspace/api-client-react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Link, useLocation } from "wouter";
import { useAuthRedirect } from "@/hooks/use-auth-redirect";
import { useEffect } from "react";
import { Store } from "lucide-react";

const loginSchema = z.object({ email: z.string().email("Enter a valid account email"), password: z.string().min(1, "Password is required") });
type LoginValues = z.infer<typeof loginSchema>;

export default function LoginPage() { const { me } = useAuthRedirect(); const [, setLocation] = useLocation(); const login = useLogin(); const form = useForm<LoginValues>({ resolver: zodResolver(loginSchema), defaultValues: { email: "", password: "" } }); useEffect(() => { if (me?.authenticated && !me?.isAdmin) setLocation("/dashboard"); if (me?.isAdmin) setLocation("/admin"); }, [me, setLocation]); const onSubmit = (data: LoginValues) => login.mutate({ data }, { onSuccess: () => setLocation("/dashboard") }); return <PublicLayout><div className="flex flex-1 items-center justify-center bg-[#f7faf8] px-4 py-12"><div className="w-full max-w-md rounded-2xl border bg-white p-8 shadow-sm"><div className="mb-7 flex flex-col items-center text-center"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary"><Store className="h-6 w-6" /></div><h1 className="mt-3 text-3xl font-extrabold text-foreground">Welcome back</h1><p className="mt-2 text-sm text-muted-foreground">Manage your WhatsApp Shop and catalogue.</p></div><form onSubmit={form.handleSubmit(onSubmit)} className="space-y-5"><div><label className="text-sm font-semibold">Account email</label><input type="email" {...form.register("email")} placeholder="you@example.com" className="mt-1 w-full rounded-xl border px-3 py-3 text-sm" />{form.formState.errors.email && <p className="mt-1 text-xs text-destructive">{form.formState.errors.email.message}</p>}</div><div><div className="flex items-center justify-between"><label className="text-sm font-semibold">Password</label><Link href="/forgot-password" className="text-xs text-primary hover:underline">Forgot password?</Link></div><input type="password" {...form.register("password")} placeholder="Your password" className="mt-1 w-full rounded-xl border px-3 py-3 text-sm" />{form.formState.errors.password && <p className="mt-1 text-xs text-destructive">{form.formState.errors.password.message}</p>}</div>{login.error && <div className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{login.error.message || "Invalid credentials"}</div>}<button type="submit" disabled={login.isPending} className="w-full rounded-xl bg-[#0a4a3a] py-3.5 text-sm font-bold text-white disabled:opacity-60">{login.isPending ? "Logging in…" : "Log in"}</button></form><p className="mt-6 text-center text-sm text-muted-foreground">New here? <Link href="/signup" className="font-semibold text-primary hover:underline">Create your shop</Link></p></div></div></PublicLayout>; }
